### ISSUE TITLE
Where can user get ServerRequestInterface?

### ISSUE THREAD

**Issue by neomerx** [nilportugues/laravel5-jsonapi-transformer#4]
Not a bug. Probably real life issue.

It's nice to comply with PSR7 however you do package for defined framework and from practical point of view how do you use `NilPortugues\Api\JsonApi\Http\Message\Request`? Using `Diactoros` or similar is overkill IMHO

```php
use \Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory;

$psr7Factory = new DiactorosFactory();
$psrRequest = $psr7Factory->createRequest($laravelRequest);
```

**Comment by neomerx** [comment]
just an idea. I had similar problem with [CORS support](https://github.com/neomerx/cors-illuminate) and used the fact that my packaged used only a few basic methods. So I created a [very thin adapter](https://github.com/neomerx/cors-illuminate/blob/master/src/Adapters/IlluminateRequestToPsr7.php) over Symfony Request.

**Comment by nilopc** [comment]
Well, thing is, I don't like attaching myself to frameworks too much. 

I'm using PSR-7's Symfony bridge because it's generic for all Symfony-component apps using its HttpFoundation. Symfony already supports PSR7 by default if brigde library is detected, but Laravel does not. 

So yeah, for the time being it's an overkill for Laravel, but I wanted to release the package fast enough. 

Definately it's an improvement that could be approached now that package is live, and I'm tagging it like that from now own
